-- CreateTable
CREATE TABLE "Tenant" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'Staff',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "theme" TEXT NOT NULL DEFAULT 'cloud-white',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "User_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "fileNumber" TEXT NOT NULL,
    "legalName" TEXT NOT NULL,
    "businessNumber" TEXT,
    "entityType" TEXT,
    "fiscalYearEnd" DATETIME NOT NULL,
    "incorporationDate" DATETIME,
    "incorporationJurisdiction" TEXT,
    "address" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "folderPath" TEXT,
    "qbPasswordEncrypted" TEXT,
    "hstApplicable" BOOLEAN NOT NULL DEFAULT false,
    "hstFrequency" TEXT,
    "payrollApplicable" BOOLEAN NOT NULL DEFAULT false,
    "payrollFrequency" TEXT,
    "remitterType" TEXT,
    "threeMonthEligible" BOOLEAN NOT NULL DEFAULT false,
    "onboardingStatus" TEXT NOT NULL DEFAULT 'Pending',
    "reviewComplete" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Client_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "FolderChecklistItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL,
    "itemName" TEXT NOT NULL,
    "created" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "FolderChecklistItem_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "HistoricalReview" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL,
    "fiscalYear" INTEGER NOT NULL,
    "filingType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'NA',
    "notes" TEXT,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "HistoricalReview_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "FilingObligation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL,
    "filingType" TEXT NOT NULL,
    "periodStart" DATETIME,
    "periodEnd" DATETIME,
    "filingDueDate" DATETIME,
    "paymentDueDate" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'NotStarted',
    "amount" REAL,
    "dateFiled" DATETIME,
    "confirmationNumber" TEXT,
    "notes" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "FilingObligation_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "entity" TEXT,
    "entityId" TEXT,
    "metadata" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Tenant_slug_key" ON "Tenant"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "User_tenantId_idx" ON "User"("tenantId");

-- CreateIndex
CREATE INDEX "Client_tenantId_idx" ON "Client"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "Client_tenantId_fileNumber_key" ON "Client"("tenantId", "fileNumber");

-- CreateIndex
CREATE UNIQUE INDEX "FolderChecklistItem_clientId_itemName_key" ON "FolderChecklistItem"("clientId", "itemName");

-- CreateIndex
CREATE UNIQUE INDEX "HistoricalReview_clientId_fiscalYear_filingType_key" ON "HistoricalReview"("clientId", "fiscalYear", "filingType");

-- CreateIndex
CREATE INDEX "FilingObligation_clientId_idx" ON "FilingObligation"("clientId");

-- CreateIndex
CREATE INDEX "FilingObligation_filingDueDate_idx" ON "FilingObligation"("filingDueDate");

-- CreateIndex
CREATE INDEX "FilingObligation_status_idx" ON "FilingObligation"("status");

-- CreateIndex
CREATE INDEX "AuditLog_tenantId_createdAt_idx" ON "AuditLog"("tenantId", "createdAt");
