/**
 * One-time data backfill for the multi-entity & jurisdiction compliance engine.
 *
 * RUN ME MANUALLY on the database, e.g.:
 *   npm run migrate-multi-entity
 *
 * The script:
 *   1. Takes a snapshot of data/app.db into backups/pre-migration/ FIRST.
 *   2. Backfills incorporationJurisdiction full names → codes (Ontario → ON).
 *   3. Backfills remitterType Regular → Monthly; Accelerated1/2 → null.
 *   4. Renames FilingObligation.filingType OntarioAnnualReturn → ProvincialAnnualReturn.
 *   5. Reconciles schedules: deletes auto-generated, Pending, future obligations
 *      that are invalid under the client's new entity type / jurisdiction.
 *      Historical / completed / non-future rows are NEVER deleted.
 *
 * Idempotent — safe to re-run.
 */

import "dotenv/config";
import { createBackupSnapshot } from "./lib/backup-snapshot";
import { prisma } from "../src/lib/prisma";
import { normalizeJurisdiction } from "../src/lib/jurisdictions";
import { filingTypesForClient } from "../src/lib/obligation-matrix";

async function main() {
  console.log("Stopping-point reminder: stop the app (stop.cmd / stop.sh) before running this.");
  console.log("Creating a backup snapshot first...");
  const snapshot = await createBackupSnapshot(undefined, "pre-multi-entity-migration");
  console.log(`Backup snapshot: ${snapshot.dbOut}\n`);

  // --- 1. Jurisdiction codes ---------------------------------------------
  const jurisdictionClients = await prisma.client.findMany({
    where: { incorporationJurisdiction: { not: null } },
    select: { id: true, incorporationJurisdiction: true },
  });
  let jurChanged = 0;
  for (const c of jurisdictionClients) {
    const normalized = normalizeJurisdiction(c.incorporationJurisdiction);
    if (normalized && normalized !== c.incorporationJurisdiction) {
      await prisma.client.update({
        where: { id: c.id },
        data: { incorporationJurisdiction: normalized },
      });
      console.log(`  jurisdiction: ${c.incorporationJurisdiction} -> ${normalized} (client ${c.id})`);
      jurChanged++;
    }
  }

  // --- 2. Remitter type ---------------------------------------------------
  const remitterClients = await prisma.client.findMany({
    where: { remitterType: { not: null } },
    select: { id: true, remitterType: true },
  });
  let remitterChanged = 0;
  for (const c of remitterClients) {
    const next =
      c.remitterType === "Regular"
        ? "Monthly"
        : c.remitterType === "Accelerated1" || c.remitterType === "Accelerated2"
          ? null
          : c.remitterType;
    if (next !== c.remitterType) {
      await prisma.client.update({ where: { id: c.id }, data: { remitterType: next } });
      console.log(`  remitter: ${c.remitterType} -> ${next ?? "null"} (client ${c.id})`);
      remitterChanged++;
    }
  }

  // --- 3. OntarioAnnualReturn -> ProvincialAnnualReturn -------------------
  const renamed = await prisma.filingObligation.updateMany({
    where: { filingType: "OntarioAnnualReturn" },
    data: { filingType: "ProvincialAnnualReturn" },
  });
  if (renamed.count > 0) console.log(`  filingType: OntarioAnnualReturn -> ProvincialAnnualReturn (${renamed.count} rows)`);

  // --- 4. Reconcile invalid Pending-future obligations -------------------
  const clients = await prisma.client.findMany({
    select: {
      id: true,
      entityType: true,
      incorporationJurisdiction: true,
      incorporationDate: true,
      hstApplicable: true,
      hstFrequency: true,
      payrollApplicable: true,
      payrollFrequency: true,
      remitterType: true,
    },
  });
  const now = Date.now();
  const deletedByType = new Map<string, number>();
  let deletedTotal = 0;

  for (const c of clients) {
    const valid = filingTypesForClient({
      entityType: c.entityType,
      incorporationJurisdiction: c.incorporationJurisdiction,
      incorporationDate: c.incorporationDate,
      hstApplicable: c.hstApplicable,
      hstFrequency: c.hstFrequency,
      payrollApplicable: c.payrollApplicable,
      payrollFrequency: c.payrollFrequency,
      remitterType: c.remitterType,
    });

    const invalid = await prisma.filingObligation.findMany({
      where: {
        clientId: c.id,
        autoGenerated: true,
        status: "Pending",
        OR: [{ filingDueDate: null }, { filingDueDate: { gte: new Date(now) } }],
      },
      select: { id: true, filingType: true },
    });

    const toDelete = invalid.filter((o) => !valid.has(o.filingType));
    if (toDelete.length > 0) {
      await prisma.filingObligation.deleteMany({
        where: { id: { in: toDelete.map((o) => o.id) } },
      });
      for (const o of toDelete) {
        deletedByType.set(o.filingType, (deletedByType.get(o.filingType) ?? 0) + 1);
      }
      deletedTotal += toDelete.length;
      console.log(`  reconcile: deleted ${toDelete.length} invalid Pending-future obligations for client ${c.id}`);
    }
  }

  // --- Summary -----------------------------------------------------------
  console.log("\n=== SUMMARY ===");
  console.log(`Jurisdiction codes updated:     ${jurChanged}`);
  console.log(`Remitter types updated:         ${remitterChanged}`);
  console.log(`OntarioAnnualReturn renamed:    ${renamed.count}`);
  console.log(`Invalid Pending-future deleted: ${deletedTotal}`);
  for (const [t, n] of [...deletedByType.entries()].sort()) {
    console.log(`  - ${t}: ${n}`);
  }
  console.log("\nDone. Existing clients may need their schedules regenerated to pick up new obligation types (Generate schedule on each client).");
}

main()
  .catch((e) => {
    console.error("[migrate-multi-entity] Fatal:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
