import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { writeAudit } from "@/lib/services/audit";
import {
  federalAnnualReturn,
  hstPeriods,
  infoReturnDeadlines,
  ontarioAnnualReturn,
  payrollRemittancePeriodsRolling,
  t2Deadlines,
  utc,
} from "@/lib/compliance-rules";
import { OBLIGATION_STATUS_VALUES } from "@/lib/obligation-status";

const OBLIGATION_STATUSES = OBLIGATION_STATUS_VALUES;

const HST_FREQUENCIES = ["Monthly", "Quarterly", "Annual", "SelfEmployed"] as const;
// Note: Accelerated1 and Accelerated2 are accepted in the form but the compliance
// rule math for them is not yet implemented — payrollRemittancePeriods returns []
// for these values, so accelerated clients won't have payroll rows generated.
const REMITTER_TYPES = ["Regular", "Quarterly", "Accelerated1", "Accelerated2"] as const;

export const updateSchema = z.object({
  status: z.enum(OBLIGATION_STATUSES).optional(),
  amount: z.number().finite().nullable().optional(),
  dateFiled: z.union([z.string(), z.date()]).nullable().optional(),
  confirmationNumber: z.string().max(100).nullable().optional(),
  notes: z.string().max(2000).nullable().optional(),
});

export type ObligationUpdate = z.infer<typeof updateSchema>;

export async function listObligationsForClient(tenantId: string, clientId: string) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return null;
  return prisma.filingObligation.findMany({
    where: { clientId },
    orderBy: [{ filingDueDate: "asc" }, { filingType: "asc" }],
  });
}

export async function listObligationsForTenant(
  tenantId: string,
  filters?: {
    from?: Date;
    to?: Date;
    status?: string;
    filingType?: string;
  }
) {
  const clients = await prisma.client.findMany({
    where: { tenantId, active: true },
    select: { id: true, fileNumber: true, legalName: true },
  });
  const clientIds = clients.map((c) => c.id);
  if (clientIds.length === 0) return { clients: [], obligations: [] };
  const where: Record<string, unknown> = { clientId: { in: clientIds } };
  if (filters?.from || filters?.to) {
    const dateFilter: Record<string, Date> = {};
    if (filters.from) dateFilter.gte = filters.from;
    if (filters.to) dateFilter.lte = filters.to;
    where.filingDueDate = dateFilter;
  }
  if (filters?.status) where.status = filters.status;
  if (filters?.filingType) where.filingType = filters.filingType;
  const obligations = await prisma.filingObligation.findMany({
    where,
    orderBy: [{ filingDueDate: "asc" }, { filingType: "asc" }],
    include: { client: { select: { id: true, fileNumber: true, legalName: true } } },
  });
  return { clients, obligations };
}

export async function generateObligationsForClient(
  tenantId: string,
  actorId: string,
  clientId: string
) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return { error: "Client not found" as const };
  if (!client.reviewComplete) {
    return { error: "Review must be complete before generating the schedule" as const };
  }

  // Delete auto-generated obligations for filing types that no longer apply
  // based on the current client configuration, so jurisdiction changes are
  // reflected. Then add only new rows that don't already exist.
  const ops: Array<ReturnType<typeof prisma.filingObligation.deleteMany> | ReturnType<typeof prisma.filingObligation.createMany>> = [];

  const jur = client.incorporationJurisdiction;
  // Remove annual returns that don't match the current jurisdiction.
  if (jur !== "Ontario") {
    ops.push(prisma.filingObligation.deleteMany({ where: { clientId, filingType: "OntarioAnnualReturn", autoGenerated: true } }));
  }
  if (jur !== "Federal") {
    ops.push(prisma.filingObligation.deleteMany({ where: { clientId, filingType: "FederalAnnualReturn", autoGenerated: true } }));
  }

  const rows: Array<{
    clientId: string;
    filingType: string;
    periodStart?: Date;
    periodEnd?: Date;
    filingDueDate?: Date;
    paymentDueDate?: Date;
    status: string;
  }> = [];
  const fye = client.fiscalYearEnd;
  const fyeYear = fye.getUTCFullYear();

  // Rolling 12-month window from the start of the current month.
  const today = new Date();
  const windowStart = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1));
  const windowEnd = new Date(windowStart);
  windowEnd.setUTCMonth(windowEnd.getUTCMonth() + 12);

  function inWindow(d: Date | null | undefined): boolean {
    if (!d) return false;
    return d.getTime() <= windowEnd.getTime();
  }

  // T2 — the upcoming T2 deadline (6mo after the most recent FYE). If that's
  // within the window, include it.
  const t2 = t2Deadlines(fye, client.threeMonthEligible);
  if (inWindow(t2.filingDue)) {
    rows.push({
      clientId,
      filingType: "T2",
      filingDueDate: t2.filingDue,
      paymentDueDate: t2.paymentDue,
      status: "Pending",
    });
  }

  // HST — generate the current FYE year and the next FYE year if it falls
  // within the window. The FYE year is the calendar year containing the FYE
  // date. For a non-Dec FYE, "current FYE year" is the year whose FYE is the
  // most recent one on or before today.
  if (
    client.hstApplicable &&
    client.hstFrequency &&
    HST_FREQUENCIES.includes(client.hstFrequency as (typeof HST_FREQUENCIES)[number])
  ) {
    const fyeForHst = client.hstFrequency as (typeof HST_FREQUENCIES)[number];
    for (const yearOffset of [0, 1]) {
      const targetFye = new Date(fye);
      targetFye.setUTCFullYear(targetFye.getUTCFullYear() + yearOffset);
      const periods = hstPeriods(targetFye, fyeForHst);
      for (const p of periods) {
        // Include this period if either its due date OR periodStart is within the
        // rolling window. The current FYE year is always included for the
        // "this month" default filter; the next FYE year is included only if
        // its first period is in the window.
        if (inWindow(p.filingDue) || (p.periodStart && p.periodStart.getTime() <= windowEnd.getTime())) {
          rows.push({
            clientId,
            filingType: "HST",
            periodStart: p.periodStart,
            periodEnd: p.periodEnd,
            filingDueDate: p.filingDue,
            paymentDueDate: p.paymentDue,
            status: "Pending",
          });
        }
      }
    }
  }

  // Annual returns — driven by incorporation jurisdiction.
  if (jur === "Ontario" || !jur) {
    const oar = ontarioAnnualReturn(fye);
    if (inWindow(oar.filingDue)) {
      rows.push({
        clientId,
        filingType: "OntarioAnnualReturn",
        periodStart: utc(fyeYear, 1, 1),
        periodEnd: fye,
        filingDueDate: oar.filingDue,
        status: "Pending",
      });
    }
  }

  if (jur === "Federal" && client.incorporationDate) {
    const far = federalAnnualReturn(client.incorporationDate);
    if (inWindow(far.filingDue)) {
      const anniversary = new Date(client.incorporationDate);
      anniversary.setUTCFullYear(anniversary.getUTCFullYear() + 1);
      const periodEnd = new Date(anniversary);
      periodEnd.setUTCDate(periodEnd.getUTCDate() + 60);
      rows.push({
        clientId,
        filingType: "FederalAnnualReturn",
        periodStart: anniversary,
        periodEnd,
        filingDueDate: far.filingDue,
        status: "Pending",
      });
    }
  }

  // T4/T4A/T5 information returns for the work year. The "work year" is the
  // FYE year. The Feb-28 filing deadline is well into the next calendar
  // year; include it if within the window.
  const info = infoReturnDeadlines(fyeYear);
  if (inWindow(info.filingDue)) {
    for (const type of ["T4", "T4A", "T5"] as const) {
      rows.push({
        clientId,
        filingType: type,
        periodStart: utc(fyeYear, 1, 1),
        periodEnd: utc(fyeYear, 12, 31),
        filingDueDate: info.filingDue,
        status: "Pending",
      });
    }
  }

  // Payroll remittances — rolling 12 months from the start of the current
  // month. For Quarterly remitter, include the 4 quarter-ends that fall
  // within the window. For Monthly, generate 12 monthly periods starting at
  // the window start.
  if (
    client.payrollApplicable &&
    client.remitterType &&
    REMITTER_TYPES.includes(client.remitterType as (typeof REMITTER_TYPES)[number])
  ) {
    const remitter = client.remitterType as (typeof REMITTER_TYPES)[number];
    const periods = payrollRemittancePeriodsRolling(windowStart, remitter);
    for (const p of periods) {
      rows.push({
        clientId,
        filingType: "PayrollRemittance",
        periodStart: p.periodStart,
        periodEnd: p.periodEnd,
        filingDueDate: p.filingDue,
        paymentDueDate: p.paymentDue,
        status: "Pending",
      });
    }
  }

  if (rows.length > 0) {
    // Only add rows that don't already exist (avoid duplicates on re-generation).
    const existing = await prisma.filingObligation.findMany({
      where: { clientId, autoGenerated: true },
      select: { filingType: true, periodStart: true, periodEnd: true, filingDueDate: true, paymentDueDate: true },
    });
    const existingSet = new Set(existing.map((e) =>
      `${e.filingType}|${e.periodStart?.getTime() ?? 0}|${e.periodEnd?.getTime() ?? 0}|${e.filingDueDate?.getTime() ?? 0}|${e.paymentDueDate?.getTime() ?? 0}`
    ));
    const newRows = rows.filter((r) =>
      !existingSet.has(`${r.filingType}|${r.periodStart?.getTime() ?? 0}|${r.periodEnd?.getTime() ?? 0}|${r.filingDueDate?.getTime() ?? 0}|${r.paymentDueDate?.getTime() ?? 0}`)
    );
    if (newRows.length > 0) {
      ops.push(prisma.filingObligation.createMany({ data: newRows }));
    }
  }
  await prisma.$transaction(ops);

  await writeAudit({
    tenantId,
    actorId,
    action: "SCHEDULE_GENERATED",
    entity: "Client",
    entityId: clientId,
    metadata: { count: rows.length },
  });

  return { count: rows.length };
}

export async function updateObligation(
  tenantId: string,
  actorId: string,
  clientId: string,
  obligationId: string,
  input: ObligationUpdate
) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return null;
  const obligation = await prisma.filingObligation.findFirst({
    where: { id: obligationId, clientId },
  });
  if (!obligation) return null;
  // Caller (the API route) is expected to have already validated `input` with
  // updateSchema. We trust the typed shape here and skip a redundant parse.

  const data: Record<string, unknown> = {};
  if (input.status !== undefined) data.status = input.status;
  if (input.amount !== undefined) data.amount = input.amount;
  if (input.confirmationNumber !== undefined) data.confirmationNumber = input.confirmationNumber;
  if (input.notes !== undefined) data.notes = input.notes;
  if (input.dateFiled !== undefined) {
    data.dateFiled =
      input.dateFiled === null
        ? null
        : input.dateFiled instanceof Date
          ? input.dateFiled
          : new Date(input.dateFiled);
  }

  const updated = await prisma.filingObligation.update({ where: { id: obligationId }, data });
  await writeAudit({
    tenantId,
    actorId,
    action: "OBLIGATION_UPDATED",
    entity: "FilingObligation",
    entityId: obligationId,
    metadata: { changes: Object.keys(data) },
  });
  return updated;
}

