import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { writeAudit } from "@/lib/services/audit";
import {
  federalAnnualReturn,
  hstPeriods,
  infoReturnDeadlines,
  ontarioAnnualReturn,
  payrollRemittancePeriods,
  t2Deadlines,
} from "@/lib/compliance-rules";

const OBLIGATION_STATUSES = [
  "NotStarted",
  "WaitingOnClient",
  "InProgress",
  "ReadyForReview",
  "Filed",
  "Overdue",
] as const;

const HST_FREQUENCIES = ["Monthly", "Quarterly", "Annual"] as const;
const REMITTER_TYPES = ["Regular", "Quarterly"] as const;

const updateSchema = z.object({
  status: z.enum(OBLIGATION_STATUSES).optional(),
  amount: z.number().finite().nullable().optional(),
  dateFiled: z.union([z.string(), z.date()]).nullable().optional(),
  confirmationNumber: z.string().max(100).nullable().optional(),
  notes: z.string().max(2000).nullable().optional(),
});

export type ObligationUpdate = z.infer<typeof updateSchema>;

export async function listObligationsForClient(tenantId: string, clientId: string) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return null;
  return prisma.filingObligation.findMany({
    where: { clientId },
    orderBy: [{ filingDueDate: "asc" }, { filingType: "asc" }],
  });
}

export async function listObligationsForTenant(
  tenantId: string,
  filters?: {
    from?: Date;
    to?: Date;
    status?: string;
    filingType?: string;
  }
) {
  const clients = await prisma.client.findMany({
    where: { tenantId, active: true },
    select: { id: true, fileNumber: true, legalName: true },
  });
  const clientIds = clients.map((c) => c.id);
  if (clientIds.length === 0) return { clients: [], obligations: [] };
  const where: Record<string, unknown> = { clientId: { in: clientIds } };
  if (filters?.from || filters?.to) {
    const dateFilter: Record<string, Date> = {};
    if (filters.from) dateFilter.gte = filters.from;
    if (filters.to) dateFilter.lte = filters.to;
    where.filingDueDate = dateFilter;
  }
  if (filters?.status) where.status = filters.status;
  if (filters?.filingType) where.filingType = filters.filingType;
  const obligations = await prisma.filingObligation.findMany({
    where,
    orderBy: [{ filingDueDate: "asc" }, { filingType: "asc" }],
    include: { client: { select: { id: true, fileNumber: true, legalName: true } } },
  });
  return { clients, obligations };
}

export async function generateObligationsForClient(
  tenantId: string,
  actorId: string,
  clientId: string
) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return { error: "Client not found" as const };
  if (!client.reviewComplete) {
    return { error: "Review must be complete before generating the schedule" as const };
  }

  // Replace any prior auto-generated obligations.
  await prisma.filingObligation.deleteMany({ where: { clientId, autoGenerated: true } });

  const rows: Array<{
    clientId: string;
    filingType: string;
    periodStart?: Date;
    periodEnd?: Date;
    filingDueDate?: Date;
    paymentDueDate?: Date;
    status: string;
  }> = [];
  const fye = client.fiscalYearEnd;
  const year = fye.getUTCFullYear();

  // T2
  const t2 = t2Deadlines(fye, client.threeMonthEligible);
  rows.push({
    clientId,
    filingType: "T2",
    filingDueDate: t2.filingDue,
    paymentDueDate: t2.paymentDue,
    status: "NotStarted",
  });

  // HST
  if (client.hstApplicable && client.hstFrequency && HST_FREQUENCIES.includes(client.hstFrequency as (typeof HST_FREQUENCIES)[number])) {
    for (const p of hstPeriods(fye, client.hstFrequency as (typeof HST_FREQUENCIES)[number])) {
      rows.push({
        clientId,
        filingType: "HST",
        periodStart: p.periodStart,
        periodEnd: p.periodEnd,
        filingDueDate: p.filingDue,
        paymentDueDate: p.paymentDue,
        status: "NotStarted",
      });
    }
  }

  // Ontario Annual Return
  const oar = ontarioAnnualReturn(fye);
  rows.push({
    clientId,
    filingType: "OntarioAnnualReturn",
    filingDueDate: oar.filingDue,
    status: "NotStarted",
  });

  // Federal Annual Return (if incorporation date known)
  if (client.incorporationDate) {
    const far = federalAnnualReturn(client.incorporationDate);
    rows.push({
      clientId,
      filingType: "FederalAnnualReturn",
      filingDueDate: far.filingDue,
      status: "NotStarted",
    });
  }

  // T4/T4A/T5 information returns for the work year
  const info = infoReturnDeadlines(year);
  for (const type of ["T4", "T4A", "T5"] as const) {
    rows.push({
      clientId,
      filingType: type,
      filingDueDate: info.filingDue,
      status: "NotStarted",
    });
  }

  // Payroll remittances
  if (
    client.payrollApplicable &&
    client.remitterType &&
    REMITTER_TYPES.includes(client.remitterType as (typeof REMITTER_TYPES)[number])
  ) {
    for (const p of payrollRemittancePeriods(
      fye,
      client.remitterType as (typeof REMITTER_TYPES)[number]
    )) {
      rows.push({
        clientId,
        filingType: "PayrollRemittance",
        periodStart: p.periodStart,
        periodEnd: p.periodEnd,
        filingDueDate: p.filingDue,
        paymentDueDate: p.paymentDue,
        status: "NotStarted",
      });
    }
  }

  if (rows.length > 0) {
    await prisma.filingObligation.createMany({ data: rows });
  }

  await writeAudit({
    tenantId,
    actorId,
    action: "SCHEDULE_GENERATED",
    entity: "Client",
    entityId: clientId,
    metadata: { count: rows.length },
  });

  return { count: rows.length };
}

export async function updateObligation(
  tenantId: string,
  actorId: string,
  clientId: string,
  obligationId: string,
  input: ObligationUpdate
) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return null;
  const obligation = await prisma.filingObligation.findFirst({
    where: { id: obligationId, clientId },
  });
  if (!obligation) return null;
  const parsed = updateSchema.safeParse(input);
  if (!parsed.success) return null;

  const data: Record<string, unknown> = {};
  if (parsed.data.status !== undefined) data.status = parsed.data.status;
  if (parsed.data.amount !== undefined) data.amount = parsed.data.amount;
  if (parsed.data.confirmationNumber !== undefined) data.confirmationNumber = parsed.data.confirmationNumber;
  if (parsed.data.notes !== undefined) data.notes = parsed.data.notes;
  if (parsed.data.dateFiled !== undefined) {
    data.dateFiled =
      parsed.data.dateFiled === null
        ? null
        : parsed.data.dateFiled instanceof Date
          ? parsed.data.dateFiled
          : new Date(parsed.data.dateFiled);
  }

  const updated = await prisma.filingObligation.update({ where: { id: obligationId }, data });
  await writeAudit({
    tenantId,
    actorId,
    action: "OBLIGATION_UPDATED",
    entity: "FilingObligation",
    entityId: obligationId,
    metadata: { changes: Object.keys(data) },
  });
  return updated;
}

export const OBLIGATION_STATUS_VALUES = OBLIGATION_STATUSES;
