import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { writeAudit } from "@/lib/services/audit";
import {
  federalAnnualReturn,
  infoReturnDeadlines,
  nextAnniversary,
  payrollRemittancePeriodsRolling,
  payrollRunPeriods,
  provincialAnnualReturnDeadline,
  salesTaxPeriods,
  t1Deadlines,
  t2Deadlines,
  t3Deadlines,
  t5013Deadlines,
  utc,
} from "@/lib/compliance-rules";
import {
  annualReturnFilingTypes,
  filingTypesForClient,
  incomeTaxFilingType,
  infoReturnFilingTypes,
  salesTaxFilingTypes,
  type ComplianceConfig,
} from "@/lib/obligation-matrix";
import { OBLIGATION_STATUS_VALUES } from "@/lib/obligation-status";

const OBLIGATION_STATUSES = OBLIGATION_STATUS_VALUES;

const HST_FREQUENCIES = ["Monthly", "Quarterly", "Annual", "SelfEmployed"] as const;
const REMITTER_TYPES = ["Monthly", "Quarterly"] as const;
const PAYROLL_FREQUENCIES = ["Weekly", "Bi-Weekly", "Semi-Monthly", "Monthly"] as const;

const SALES_TAX_TYPES = ["HST", "GST", "GSTQST", "PST", "RST"] as const;

export const updateSchema = z.object({
  status: z.enum(OBLIGATION_STATUSES).optional(),
  amount: z.number().finite().nullable().optional(),
  dateFiled: z.union([z.string(), z.date()]).nullable().optional(),
  confirmationNumber: z.string().max(100).nullable().optional(),
  notes: z.string().max(2000).nullable().optional(),
});

export type ObligationUpdate = z.infer<typeof updateSchema>;

export async function listObligationsForClient(tenantId: string, clientId: string) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return null;
  return prisma.filingObligation.findMany({
    where: { clientId },
    orderBy: [{ filingDueDate: "asc" }, { filingType: "asc" }],
  });
}

export async function listObligationsForTenant(
  tenantId: string,
  filters?: {
    from?: Date;
    to?: Date;
    status?: string;
    filingType?: string;
  }
) {
  const clients = await prisma.client.findMany({
    where: { tenantId, active: true },
    select: { id: true, fileNumber: true, legalName: true },
  });
  const clientIds = clients.map((c) => c.id);
  if (clientIds.length === 0) return { clients: [], obligations: [] };
  const where: Record<string, unknown> = { clientId: { in: clientIds } };
  if (filters?.from || filters?.to) {
    const dateFilter: Record<string, Date> = {};
    if (filters.from) dateFilter.gte = filters.from;
    if (filters.to) dateFilter.lte = filters.to;
    where.filingDueDate = dateFilter;
  }
  if (filters?.status) where.status = filters.status;
  if (filters?.filingType) where.filingType = filters.filingType;
  const obligations = await prisma.filingObligation.findMany({
    where,
    orderBy: [{ filingDueDate: "asc" }, { filingType: "asc" }],
    include: { client: { select: { id: true, fileNumber: true, legalName: true } } },
  });
  return { clients, obligations };
}

/**
 * Auto-generated, Pending, future obligations whose filing type is not in the
 * set the given config would generate. Used by the safe-edit flow (Phase 5) to
 * confirm before purging, and by the reconciliation backfill. Historical and
 * completed rows are never returned.
 */
export async function findInvalidPendingObligations(
  clientId: string,
  config: ComplianceConfig
) {
  const valid = filingTypesForClient(config);
  const rows = await prisma.filingObligation.findMany({
    where: {
      clientId,
      autoGenerated: true,
      status: "Pending",
      OR: [{ filingDueDate: null }, { filingDueDate: { gte: new Date() } }],
      filingType: { notIn: [...valid] },
    },
    select: { id: true, filingType: true },
  });
  return rows;
}

export async function generateObligationsForClient(
  tenantId: string,
  actorId: string,
  clientId: string
) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return { error: "Client not found" as const };
  if (!client.reviewComplete) {
    return { error: "Review must be complete before generating the schedule" as const };
  }

  const ops: Array<ReturnType<typeof prisma.filingObligation.deleteMany> | ReturnType<typeof prisma.filingObligation.createMany>> = [];

  const config: ComplianceConfig = {
    entityType: client.entityType,
    incorporationJurisdiction: client.incorporationJurisdiction,
    incorporationDate: client.incorporationDate,
    hstApplicable: client.hstApplicable,
    hstFrequency: client.hstFrequency,
    payrollApplicable: client.payrollApplicable,
    payrollFrequency: client.payrollFrequency,
    remitterType: client.remitterType,
  };
  const validTypes = filingTypesForClient(config);

  const rows: Array<{
    clientId: string;
    filingType: string;
    periodStart?: Date;
    periodEnd?: Date;
    filingDueDate?: Date;
    paymentDueDate?: Date | null;
    status: string;
  }> = [];
  const fye = client.fiscalYearEnd;
  const fyeYear = fye.getUTCFullYear();
  const jur = client.incorporationJurisdiction;

  // Rolling 12-month window from the start of the current month.
  const today = new Date();
  const windowStart = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1));
  const windowEnd = new Date(windowStart);
  windowEnd.setUTCMonth(windowEnd.getUTCMonth() + 12);

  function inWindow(d: Date | null | undefined): boolean {
    if (!d) return false;
    // Lower bound too: don't re-generate stale rows from before the window start.
    return d.getTime() >= windowStart.getTime() && d.getTime() <= windowEnd.getTime();
  }

  function periodOverlapsWindow(p: { periodStart?: Date | null; periodEnd?: Date | null }): boolean {
    return !!p.periodStart && !!p.periodEnd &&
      p.periodStart.getTime() <= windowEnd.getTime() &&
      p.periodEnd.getTime() >= windowStart.getTime();
  }

  // Fiscal year start: the day after the prior FYE.
  const fyeStart = (() => {
    const s = new Date(fye);
    s.setUTCMonth(s.getUTCMonth() - 12);
    s.setUTCDate(s.getUTCDate() + 1);
    return s;
  })();

  // Reconcile: purge auto-generated, Pending, future rows whose filing type is
  // no longer valid for this entity/jurisdiction. Historical and completed rows
  // are never touched.
  const stale = await prisma.filingObligation.findMany({
    where: {
      clientId,
      autoGenerated: true,
      status: "Pending",
      OR: [{ filingDueDate: null }, { filingDueDate: { gte: today } }],
      filingType: { notIn: [...validTypes] },
    },
    select: { id: true },
  });
  if (stale.length > 0) {
    ops.push(prisma.filingObligation.deleteMany({ where: { id: { in: stale.map((s) => s.id) } } }));
  }

  // ---- Income tax (exactly one, by entity type) ----
  const incomeType = incomeTaxFilingType(client.entityType);
  if (incomeType === "T2") {
    const t2 = t2Deadlines(fye, client.threeMonthEligible);
    if (inWindow(t2.filingDue)) {
      rows.push({
        clientId,
        filingType: "T2",
        periodStart: fyeStart,
        periodEnd: fye,
        filingDueDate: t2.filingDue,
        paymentDueDate: t2.paymentDue,
        status: "Pending",
      });
    }
  } else if (incomeType === "T1") {
    const d = t1Deadlines(fyeYear, client.entityType === "Individual");
    if (inWindow(d.filingDue)) {
      rows.push({
        clientId,
        filingType: "T1",
        periodStart: utc(fyeYear, 1, 1),
        periodEnd: utc(fyeYear, 12, 31),
        filingDueDate: d.filingDue,
        paymentDueDate: d.paymentDue,
        status: "Pending",
      });
    }
  } else if (incomeType === "T5013") {
    const d = t5013Deadlines(fyeYear);
    if (inWindow(d.filingDue)) {
      rows.push({
        clientId,
        filingType: "T5013",
        periodStart: utc(fyeYear, 1, 1),
        periodEnd: utc(fyeYear, 12, 31),
        filingDueDate: d.filingDue,
        paymentDueDate: d.paymentDue,
        status: "Pending",
      });
    }
  } else if (incomeType === "T3") {
    const d = t3Deadlines(fye);
    if (inWindow(d.filingDue)) {
      rows.push({
        clientId,
        filingType: "T3",
        periodStart: fyeStart,
        periodEnd: fye,
        filingDueDate: d.filingDue,
        paymentDueDate: d.paymentDue,
        status: "Pending",
      });
    }
  }

  // ---- Sales tax (gated by hstApplicable + hstFrequency; jurisdiction picks
  // the filings: HST / GST / GST/QST / GST+PST|RST). Monthly is anchored to the
  // rolling window; other frequencies use the gstYearEnd/FYE anchor.
  if (
    client.hstApplicable &&
    client.hstFrequency &&
    HST_FREQUENCIES.includes(client.hstFrequency as (typeof HST_FREQUENCIES)[number])
  ) {
    const frequency = client.hstFrequency as (typeof HST_FREQUENCIES)[number];
    const filingTypes = salesTaxFilingTypes(jur);
    const periods = salesTaxPeriods({
      windowStart,
      fye,
      frequency,
      gstYearEnd: client.gstYearEnd,
      entityType: client.entityType,
    });
    for (const filingType of filingTypes) {
      for (const p of periods) {
        if (inWindow(p.filingDue) || periodOverlapsWindow(p)) {
          rows.push({
            clientId,
            filingType,
            periodStart: p.periodStart,
            periodEnd: p.periodEnd,
            filingDueDate: p.filingDue,
            paymentDueDate: p.paymentDue,
            status: "Pending",
          });
        }
      }
    }
  }

  // ---- Corporate annual returns (suppressed for non-Corporation entities) ----
  const arTypes = annualReturnFilingTypes(config);
  if (arTypes.includes("FederalAnnualReturn") && client.incorporationDate) {
    const far = federalAnnualReturn(client.incorporationDate);
    if (inWindow(far.filingDue)) {
      const periodEnd = far.filingDue;
      const periodStart = new Date(periodEnd);
      periodStart.setUTCDate(periodStart.getUTCDate() - 60);
      rows.push({
        clientId,
        filingType: "FederalAnnualReturn",
        periodStart,
        periodEnd,
        filingDueDate: far.filingDue,
        status: "Pending",
      });
    }
  }
  if (arTypes.includes("ProvincialAnnualReturn")) {
    const due = provincialAnnualReturnDeadline(jur, fye, client.incorporationDate);
    if (due && inWindow(due)) {
      const isFyeBased = jur === "ON" || jur === "QC";
      const periodEnd = isFyeBased
        ? fye
        : client.incorporationDate
          ? nextAnniversary(client.incorporationDate)
          : due;
      const periodStart = new Date(periodEnd);
      periodStart.setUTCFullYear(periodStart.getUTCFullYear() - 1);
      rows.push({
        clientId,
        filingType: "ProvincialAnnualReturn",
        periodStart,
        periodEnd,
        filingDueDate: due,
        status: "Pending",
      });
    }
  }

  // ---- Info returns (entity-aware) ----
  const infoTypes = infoReturnFilingTypes(config);
  if (infoTypes.includes("T3Slips")) {
    const d = t3Deadlines(fye);
    if (inWindow(d.filingDue)) {
      rows.push({
        clientId,
        filingType: "T3Slips",
        periodStart: fyeStart,
        periodEnd: fye,
        filingDueDate: d.filingDue,
        status: "Pending",
      });
    }
  } else if (infoTypes.length > 0) {
    const info = infoReturnDeadlines(fyeYear);
    if (inWindow(info.filingDue)) {
      for (const type of infoTypes) {
        rows.push({
          clientId,
          filingType: type,
          periodStart: utc(fyeYear, 1, 1),
          periodEnd: utc(fyeYear, 12, 31),
          filingDueDate: info.filingDue,
          status: "Pending",
        });
      }
    }
  }

  // ---- Payroll remittances (Monthly → 15th of following month; Quarterly → 15th after quarter-end) ----
  if (
    client.payrollApplicable &&
    client.remitterType &&
    REMITTER_TYPES.includes(client.remitterType as (typeof REMITTER_TYPES)[number])
  ) {
    const remitter = client.remitterType as (typeof REMITTER_TYPES)[number];
    const periods = payrollRemittancePeriodsRolling(windowStart, remitter);
    for (const p of periods) {
      rows.push({
        clientId,
        filingType: "PayrollRemittance",
        periodStart: p.periodStart,
        periodEnd: p.periodEnd,
        filingDueDate: p.filingDue,
        paymentDueDate: p.paymentDue,
        status: "Pending",
      });
    }
  }

  // ---- Employee payroll processing runs, driven by pay frequency ----
  if (
    client.payrollApplicable &&
    client.payrollFrequency &&
    PAYROLL_FREQUENCIES.includes(client.payrollFrequency as (typeof PAYROLL_FREQUENCIES)[number])
  ) {
    const frequency = client.payrollFrequency as (typeof PAYROLL_FREQUENCIES)[number];
    for (const p of payrollRunPeriods(windowStart, frequency)) {
      if (!inWindow(p.filingDue)) continue;
      rows.push({
        clientId,
        filingType: "PayrollProcessing",
        periodStart: p.periodStart,
        periodEnd: p.periodEnd,
        filingDueDate: p.filingDue,
        paymentDueDate: p.paymentDue,
        status: "Pending",
      });
    }
  }

  if (rows.length > 0) {
    // Only add rows that don't already exist (avoid duplicates on re-generation).
    const existing = await prisma.filingObligation.findMany({
      where: { clientId, autoGenerated: true },
      select: { filingType: true, periodStart: true, periodEnd: true, filingDueDate: true, paymentDueDate: true },
    });
    const existingSet = new Set(existing.map((e) =>
      `${e.filingType}|${e.periodStart?.getTime() ?? 0}|${e.periodEnd?.getTime() ?? 0}|${e.filingDueDate?.getTime() ?? 0}|${e.paymentDueDate?.getTime() ?? 0}`
    ));
    const newRows = rows.filter((r) =>
      !existingSet.has(`${r.filingType}|${r.periodStart?.getTime() ?? 0}|${r.periodEnd?.getTime() ?? 0}|${r.filingDueDate?.getTime() ?? 0}|${r.paymentDueDate?.getTime() ?? 0}`)
    );
    if (newRows.length > 0) {
      ops.push(prisma.filingObligation.createMany({ data: newRows }));
    }
  }
  await prisma.$transaction(ops);

  await writeAudit({
    tenantId,
    actorId,
    action: "SCHEDULE_GENERATED",
    entity: "Client",
    entityId: clientId,
    metadata: { count: rows.length },
  });

  const warnings: string[] = [];

  // Check for configs that silently produce zero sales-tax obligations.
  const salesApplied = client.hstApplicable && client.hstFrequency;
  const hasSalesRows = rows.some((r) => (SALES_TAX_TYPES as readonly string[]).includes(r.filingType));
  const seAnnualRule =
    (client.hstFrequency === "SelfEmployed" ||
      (client.hstFrequency === "Annual" &&
        (client.entityType === "Self-Employed" || client.entityType === "Individual"))) &&
    (fye.getUTCMonth() !== 11 || fye.getUTCDate() !== 31);
  if (salesApplied && !hasSalesRows && seAnnualRule) {
    warnings.push(
      "Sales tax for this entity/frequency requires a December 31 fiscal year-end. No sales tax periods were generated."
    );
  }

  // Provincial AR: anniversary-based provinces need an incorporation date to
  // compute the filing deadline. If one is expected but the date is missing,
  // surface a warning instead of silently skipping the obligation.
  const hasProvincialAr = rows.some((r) => r.filingType === "ProvincialAnnualReturn");
  const needsIncDate =
    jur && jur !== "Federal" && jur !== "ON" && jur !== "QC" && !client.incorporationDate;
  if (arTypes.includes("ProvincialAnnualReturn") && !hasProvincialAr && needsIncDate) {
    warnings.push(
      `Provincial Annual Return for ${jur} is due from the incorporation anniversary, which requires an incorporation date. Add the incorporation date and regenerate the schedule.`
    );
  }

  return { count: rows.length, warnings };
}

export async function updateObligation(
  tenantId: string,
  actorId: string,
  clientId: string,
  obligationId: string,
  input: ObligationUpdate
) {
  const client = await prisma.client.findFirst({ where: { id: clientId, tenantId } });
  if (!client) return null;
  const obligation = await prisma.filingObligation.findFirst({
    where: { id: obligationId, clientId },
  });
  if (!obligation) return null;
  // Caller (the API route) is expected to have already validated `input` with
  // updateSchema. We trust the typed shape here and skip a redundant parse.

  const data: Record<string, unknown> = {};
  if (input.status !== undefined) data.status = input.status;
  if (input.amount !== undefined) data.amount = input.amount;
  if (input.confirmationNumber !== undefined) data.confirmationNumber = input.confirmationNumber;
  if (input.notes !== undefined) data.notes = input.notes;
  if (input.dateFiled !== undefined) {
    data.dateFiled =
      input.dateFiled === null
        ? null
        : input.dateFiled instanceof Date
          ? input.dateFiled
          : new Date(input.dateFiled);
  }

  const updated = await prisma.filingObligation.update({ where: { id: obligationId }, data });
  await writeAudit({
    tenantId,
    actorId,
    action: "OBLIGATION_UPDATED",
    entity: "FilingObligation",
    entityId: obligationId,
    metadata: { changes: Object.keys(data) },
  });
  return updated;
}

